name: Build for Windows

on:
  workflow_dispatch: # Allow manual execution

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install Dependencies
        run: |
          choco install make -y
          # Install MSYS2 which provides MinGW toolchain with OpenGL headers
          choco install msys2 -y
          # Update MSYS2 and install required packages
          C:\tools\msys64\usr\bin\bash -lc "pacman --noconfirm -Syu"
          C:\tools\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-gcc mingw-w64-x86_64-pkg-config mingw-w64-x86_64-opengl-headers"
          # Add MinGW to PATH
          echo "C:\tools\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          make test
        continue-on-error: false

      - name: Build for Windows
        run: |
          make build GOGG_BINARY=gogg.exe
        continue-on-error: false

      - name: List Build Directory (for Debugging)
        run: ls -R bin

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gogg-windows-amd64
          path: 'bin/gogg.exe'
