name: MacOS Build

on:
  workflow_dispatch: # Allow manual execution

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install Dependencies
        run: |
          brew install make
          make test
        continue-on-error: false

      - name: Build for MacOS
        run: |
          make build-macos
        continue-on-error: false

      - name: List Build Directory (for Debugging)
        run: ls -R bin

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gogg-macos-universal
          path: 'bin/gogg'
