name: Build for Windows

on:
  workflow_dispatch: # Allow manual execution

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      # Use setup-msys2 action for installing MSYS2/MinGW components
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64 # Use the MinGW-w64 64-bit environment
          update: true      # Update MSYS2 database and packages
          install: >-       # Install required packages using pacman
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-freeglut # This package usually provides the OpenGL headers

      - name: Run Tests
        shell: msys2 {0}
        run: |
          make test

      - name: Build for Windows
        shell: msys2 {0}
        run: |
          make build GOGG_BINARY=gogg.exe

      - name: List Build Directory (for Debugging)
        shell: msys2 {0}
        run: ls -R bin

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gogg-windows-amd64
          path: 'bin/gogg.exe'
