name: Build for MacOS

on:
  workflow_dispatch: # Allow manual execution

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install Dependencies
        run: |
          brew install make
          # Install OpenGL and GLFW dependencies
          brew install pkg-config
          # macOS already includes OpenGL framework
          # Install additional X11-related dependencies that might be needed
          brew install glfw

      - name: Run Tests
        run: |
          make test

      - name: Build for MacOS
        run: |
          make build-macos

      - name: List Build Directory (for Debugging)
        run: ls -R bin

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gogg-macos-universal
          path: 'bin/gogg'
