name: Build for Linux

on:
  workflow_dispatch: # Allow manual execution

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install Dependencies
        run: |
          sudo apt-get update
          make install-deps

      - name: Run Tests
        run: |
          make test

      - name: Build for Linux
        run: |
          make build

      - name: List Build Directory (for Debugging)
        run: ls -R bin

      - name: Test CLI API
        run: bash test_gogg_cli.sh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gogg-linux-amd64
          path: 'bin/gogg'
