name: Run Linters

on:
    workflow_dispatch: # Allow manual execution
    push:
        tags:
            - 'v*' # Trigger on version tags

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version: '1.23'

            -   name: Install golangci-lint
                run: |
                    make install-deps

            -   name: Run golangci-lint
                run: |
                    make lint
