name: Tests

on:
    workflow_dispatch: # Only enable manual runs for now

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                # Define the Go versions to test against
                go-version: [ "1.21", "1.22", "1.23" ]

        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v4

            -   name: Set up Go ${{ matrix.go-version }}
                uses: actions/setup-go@v5
                with:
                    go-version: ${{ matrix.go-version }}

            # Install dependencies and run the tests
            -   name: Install Dependencies
                run: |
                    sudo apt-get install -y make
                    make format
                continue-on-error: false

            -   name: Run Tests and Generate Coverage Report
                run: |
                    make test
                    make codecov
                continue-on-error: false

            # Upload the coverage report to Codecov
            -   name: Upload coverage reports to Codecov
                uses: codecov/codecov-action@v5
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
